# Generated by Django 5.0.7 on 2024-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.BigIntegerField()),
                ('area', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('major_cities', models.CharField(max_length=200)),
                ('climate', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
    ]
