# Generated by Django 5.0.7 on 2024-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='climate',
            field=models.CharField(max_length=200),
        ),
    ]
